name: TMAS Scan

on:
  pull_request:

permissions:
  pull-requests: write
  contents: read

jobs:
  scan:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run TMAS Scan
        uses: trendmicro/tmas-scan-action@main
        with:
          artifact: "registry:docker.io/library/nginx:latest"
          region: "us-east-1"
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          TMAS_API_KEY: ${{ secrets.TMAS_API_KEY }}